create table users
(
    id             integer not null
        primary key,
    full_name      text,
    first_name     text,
    last_name      text,
    username       text,
    avatar         text,
    email          text,
    email_verified boolean,
    phone          text,
    twitter_handle text,
    bio            text
);

alter table users
    owner to postgres;

INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (1, 'Susan Williamson', 'Susan', 'Williamson', 'sWilliamson', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-00.png', 'Kyla_Considine@hotmail.com', true, '808.797.1741', 'sWilliamson', 'Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (2, 'Henrietta Wagner', 'Henrietta', 'Wagner', 'hWagner', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-01.png', 'Betsy46@gmail.com', true, '903-894-7300', 'hWagner', 'Travel lover. Explorer. Analyst. Subtly charming pop culture aficionado. Friendly creator.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (3, 'Lydia Snyder', 'Lydia', 'Snyder', 'lSnyder', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-02.png', 'Jordi.Mayert@hotmail.com', false, '1-690-361-8055 x579', 'lSnyder', 'Coffee expert. Tv nerd. Proud music fan. Bacon guru. Analyst. Subtly charming gamer.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (4, 'Harold Herrera', 'Harold', 'Herrera', 'hHerrera', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-03.png', 'Hope_Anderson93@gmail.com', false, '550-705-6463 x76546', 'hHerrera', 'Creator. Unapologetic introvert. Coffee evangelist. Evil music enthusiast. Bacon trailblazer. Troublemaker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (5, 'Richard Garrett', 'Richard', 'Garrett', 'rGarrett', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-04.png', 'Tobin_Streich9@yahoo.com', false, '967.481.3949 x0203', 'rGarrett', 'Travel fanatic. Devoted explorer. Social media maven. Proud analyst. Bacon geek. Zombie ninja. Problem solver. Student. Amateur alcohol practitioner. Thinker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (6, 'Lee Bates', 'Lee', 'Bates', 'lBates', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-05.png', 'Maye.Miller@hotmail.com', true, '228.972.8913 x86724', 'lBates', 'Music ninja. Friend of animals everywhere. Lifelong thinker. Alcohol scholar. Social media expert.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (7, 'Jesus Newman', 'Jesus', 'Newman', 'jNewman', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-06.png', 'Ceasar_Sanford3@hotmail.com', false, '741-463-9786', 'jNewman', 'Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (8, 'Polly Kennedy', 'Polly', 'Kennedy', 'pKennedy', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-07.png', 'Kendrick_Tromp@hotmail.com', false, '727.246.2165 x3061', 'pKennedy', 'Travel lover. Explorer. Analyst. Subtly charming pop culture aficionado. Friendly creator.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (9, 'Augusta Stevenson', 'Augusta', 'Stevenson', 'aStevenson', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-08.png', 'Ofelia_Lehner24@yahoo.com', true, '1-992-487-8671 x46778', 'aStevenson', 'Coffee expert. Tv nerd. Proud music fan. Bacon guru. Analyst. Subtly charming gamer.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (10, 'Tyler Perkins', 'Tyler', 'Perkins', 'tPerkins', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-09.png', 'Leda20@gmail.com', false, '870.226.2928', 'tPerkins', 'Creator. Unapologetic introvert. Coffee evangelist. Evil music enthusiast. Bacon trailblazer. Troublemaker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (11, 'Allie Burns', 'Allie', 'Burns', 'aBurns', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-10.png', 'Justina67@gmail.com', false, '220.706.3173', 'aBurns', 'Travel fanatic. Devoted explorer. Social media maven. Proud analyst. Bacon geek. Zombie ninja. Problem solver. Student. Amateur alcohol practitioner. Thinker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (12, 'Gordon Murray', 'Gordon', 'Murray', 'gMurray', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-11.png', 'Polly22@gmail.com', true, '1-368-257-6876', 'gMurray', 'Music ninja. Friend of animals everywhere. Lifelong thinker. Alcohol scholar. Social media expert.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (13, 'Ronald Casey', 'Ronald', 'Casey', 'rCasey', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-12.png', 'Daniela.Barton@gmail.com', true, '1-772-620-7291', 'rCasey', 'Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (14, 'Rodney Malone', 'Rodney', 'Malone', 'rMalone', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-13.png', 'Jane.Hettinger@hotmail.com', true, '447-239-0002 x5891', 'rMalone', 'Travel lover. Explorer. Analyst. Subtly charming pop culture aficionado. Friendly creator.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (15, 'Louis Sandoval', 'Louis', 'Sandoval', 'lSandoval', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-14.png', 'Linnie_Predovic@yahoo.com', true, '809.788.1344', 'lSandoval', 'Coffee expert. Tv nerd. Proud music fan. Bacon guru. Analyst. Subtly charming gamer.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (16, 'Antonio Pierce', 'Antonio', 'Pierce', 'aPierce', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-15.png', 'Demetrius.Medhurst@hotmail.com', false, '296-305-8382 x0423', 'aPierce', 'Creator. Unapologetic introvert. Coffee evangelist. Evil music enthusiast. Bacon trailblazer. Troublemaker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (17, 'Joe Myers', 'Joe', 'Myers', 'jMyers', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-16.png', 'Christiana_Pollich@hotmail.com', true, '680-320-5906', 'jMyers', 'Travel fanatic. Devoted explorer. Social media maven. Proud analyst. Bacon geek. Zombie ninja. Problem solver. Student. Amateur alcohol practitioner. Thinker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (18, 'Manuel Moss', 'Manuel', 'Moss', 'mMoss', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-17.png', 'Alva.Macejkovic46@hotmail.com', true, '(751) 984-4844', 'mMoss', 'Music ninja. Friend of animals everywhere. Lifelong thinker. Alcohol scholar. Social media expert.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (19, 'George Johnson', 'George', 'Johnson', 'gJohnson', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-18.png', 'Enrique.Spinka@yahoo.com', true, '879.780.7911', 'gJohnson', 'Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (20, 'Jose Curry', 'Jose', 'Curry', 'jCurry', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-00.png', 'Merle.Keeling5@gmail.com', true, '594-630-5581', 'jCurry', 'Travel lover. Explorer. Analyst. Subtly charming pop culture aficionado. Friendly creator.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (21, 'Elva Brock', 'Elva', 'Brock', 'eBrock', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-01.png', 'Susana.Mayer49@hotmail.com', true, '421-704-9122 x822', 'eBrock', 'Coffee expert. Tv nerd. Proud music fan. Bacon guru. Analyst. Subtly charming gamer.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (22, 'Mittie Rodriguez', 'Mittie', 'Rodriguez', 'mRodriguez', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-02.png', 'Jasper.Runolfsson85@hotmail.com', false, '1-348-884-1254', 'mRodriguez', 'Creator. Unapologetic introvert. Coffee evangelist. Evil music enthusiast. Bacon trailblazer. Troublemaker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (23, 'Dylan Valdez', 'Dylan', 'Valdez', 'dValdez', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-03.png', 'Chauncey.Romaguera37@yahoo.com', true, '1-886-697-4093 x13638', 'dValdez', 'Travel fanatic. Devoted explorer. Social media maven. Proud analyst. Bacon geek. Zombie ninja. Problem solver. Student. Amateur alcohol practitioner. Thinker.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (24, 'Evelyn Ray', 'Evelyn', 'Ray', 'eRay', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-04.png', 'Yasmine_Jenkins@yahoo.com', false, '1-721-479-4097 x97303', 'eRay', 'Music ninja. Friend of animals everywhere. Lifelong thinker. Alcohol scholar. Social media expert.');
INSERT INTO public.users (id, full_name, first_name, last_name, username, avatar, email, email_verified, phone, twitter_handle, bio) VALUES (25, 'Matilda Castillo', 'Matilda', 'Castillo', 'mCastillo', 'https://sauibakeryprod.blob.core.windows.net/mock-database-assets/users-avatars/user-05.png', 'Christ.Brown@hotmail.com', true, '480.726.9164 x161', 'mCastillo', 'Friendly music geek. Organizer. Twitter scholar. Creator. General food nerd. Future teen idol. Thinker.');
